- name: Install Apache on web servers
  hosts: web
  become: true
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present

- name: Install MariaDB on db servers
  hosts: db
  become: true
  tasks:
    - name: Install MariaDB
      yum:
        name: mariadb-server
        state: present
